// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project.Infrastructure.Data;

#nullable disable

namespace escuela.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250923183045_InitialCreate2")]
    partial class InitialCreate2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("escuela.Domain.Alumno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EscuelaId")
                        .HasColumnType("int");

                    b.Property<int>("MadreId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PadreId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EscuelaId");

                    b.HasIndex("MadreId");

                    b.HasIndex("PadreId");

                    b.ToTable("Alumnos");
                });

            modelBuilder.Entity("escuela.Domain.Escuela", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Escuelas");
                });

            modelBuilder.Entity("escuela.Domain.Padre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Padres");
                });

            modelBuilder.Entity("escuela.Domain.Alumno", b =>
                {
                    b.HasOne("escuela.Domain.Escuela", "Escuela")
                        .WithMany("Alumnos")
                        .HasForeignKey("EscuelaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("escuela.Domain.Padre", "Madre")
                        .WithMany("HijosComoMadre")
                        .HasForeignKey("MadreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("escuela.Domain.Padre", "Padre")
                        .WithMany("HijosComoPadre")
                        .HasForeignKey("PadreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Escuela");

                    b.Navigation("Madre");

                    b.Navigation("Padre");
                });

            modelBuilder.Entity("escuela.Domain.Escuela", b =>
                {
                    b.Navigation("Alumnos");
                });

            modelBuilder.Entity("escuela.Domain.Padre", b =>
                {
                    b.Navigation("HijosComoMadre");

                    b.Navigation("HijosComoPadre");
                });
#pragma warning restore 612, 618
        }
    }
}
